version: '3.8'

services:
  googlecalendartoluma-cron:
    build: .
    container_name: googlecalendartoluma-cron
    volumes:
      - ../luma_payloads:/app/luma_payloads
    environment:
      - GCAL_EMBED_URL=${GCAL_EMBED_URL:-https://calendar.google.com/calendar/embed?src=tnti8oguf84qd354budk86vdpk%40group.calendar.google.com&ctz=America%2FNew_York}
      - LUMA_CALENDAR_API_ID=${LUMA_CALENDAR_API_ID:-cal-iPlAn4RA1wD1lDh}
      - COVER_URL=${COVER_URL:-https://images.lumacdn.com/gallery-images/vn/e95edc2d-7ad2-45a0-ba4c-393e17cb8f60}
      - TINT_COLOR=${TINT_COLOR:-#708967}
      - FONT_TITLE=${FONT_TITLE:-geist-mono}
      - TIMEZONE_NAME=${TIMEZONE_NAME:-America/New_York}
      - LIMIT=${LIMIT:-5}
      - OUT_DIR=${OUT_DIR:-luma_payloads}
    command: ["python", "main.py"]

