# Production environment overrides
# Used by GitHub Actions when environment=prod

fullnameOverride: "googlecalendartoluma-api"

# Allow Kubernetes to pull from GHCR
imagePullSecrets:
  - name: ghcr-login

config:
  # Show more events in prod than dev
  limit: 5

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80